import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  test.slow();
  await page.goto('https://demoqa.com/');
  await page.waitForLoadState();
  await page.locator('div:nth-child(2) > div > .avatar > svg').click();
  await page.getByRole('listitem').click();
  await page.getByPlaceholder('First Name').fill('Jhon');
  await page.getByPlaceholder('Last Name').fill('Doe');
  await page.getByPlaceholder('name@example.com').fill('j.doe@gmail.com');
  await page.getByText('Male', { exact: true }).click();
  await page.getByText('Female').click();
  await page.getByText('Other').click();
  await page.getByText('Male', { exact: true }).click();
  await page.getByPlaceholder('Mobile Number').fill('3257852325');
  await page.locator('#dateOfBirthInput').click();
  await page.locator('div').filter({ hasText: /^JanuaryFebruaryMarchAprilMayJuneJulyAugustSeptemberOctoberNovemberDecember$/ }).getByRole('combobox').selectOption('4');
  await page.getByRole('combobox').nth(1).selectOption('2008');
  await page.getByLabel('Choose Tuesday, April 29th,').click();
  await page.locator('.subjects-auto-complete__value-container').click();
  await page.locator('#subjectsInput').click();
  await page.locator('#subjectsInput').fill('English');
  await page.locator("#react-select-2-option-0").click();
  await page.locator('#subjectsInput').fill('Biology');
  await page.locator("#react-select-2-option-0").click();
  await page.locator('#subjectsInput').fill('Social Studies');
  await page.locator("#react-select-2-option-0").click();
  await page.locator('#subjectsInput').fill('Maths');
  await page.locator("#react-select-2-option-0").click();
  await page.locator('#subjectsInput').fill('Accounting');
  await page.locator("#react-select-2-option-0").click();
  await page.locator('#subjectsInput').fill('Arts');
  await page.locator("#react-select-2-option-0").click();
  await page.locator('#subjectsInput').fill('Chemistry');
  await page.locator("#react-select-2-option-0").click();
  await page.locator('#subjectsInput').fill('Civics');
  await page.locator("#react-select-2-option-0").click();
  await page.locator('#subjectsInput').fill('Physics');
  await page.locator("#react-select-2-option-0").click();
  await page.locator('#subjectsInput').fill('Commerce');
  await page.locator("#react-select-2-option-0").click();
  await page.locator('#subjectsInput').fill('Computer Science');
  await page.locator("#react-select-2-option-0").click();
  await page.locator('#subjectsInput').fill('Economics');
  await page.locator("#react-select-2-option-0").click();
  await page.locator('#subjectsInput').fill('History');
  await page.locator("#react-select-2-option-0").click();
  await page.locator('#subjectsInput').fill('Hindi');
  await page.locator("#react-select-2-option-0").click();

  await page.getByText('Sports').click();
  await page.getByText('Reading').click();
  await page.getByText('Music').click();
  await page.getByLabel('Select picture').click();
  await page.getByLabel('Select picture').setInputFiles('Materias.xlsx');
  await page.getByPlaceholder('Current Address').fill('1245 Brookling RD New York, New York 25625 USA');
  await page.locator('#state > .css-yk16xz-control > .css-1wy0on6 > .css-tlfecz-indicatorContainer').click();
  await page.getByText('Uttar Pradesh', { exact: true }).click();
  await page.locator('#city svg').click();
  await page.getByText('Agra', { exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
});